# Generated by Django 4.2 on 2023-04-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_alter_category_options_product_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_intent',
            new_name='Telephone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='is_performed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
