# Generated by Django 4.2 on 2023-07-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_payment_intent_order_telephone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_performed',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_performed',
            field=models.BooleanField(default=False),
        ),
    ]
